name: Clair Default Action Scan

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  docker-build:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Set up Clair
        shell: bash
        run: |
          curl -L \
            https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 \
            -o clair-scanner && \
            chmod +x ./clair-scanner
          docker run -d --name clair-db arminc/clair-db:latest
          docker run -p 6060:6060 --link clair-db:postgres -d --name clair arminc/clair-local-scan:latest

      - name: Scan image with Clair
        shell: bash
        run: |
          ip=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
          ./clair-scanner --ip $ip myimage
