name: Clair Dockerfile Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clair_scan:
    name: Clair Dockerfile Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Install Clair scanner
        run: |
          sudo apt-get update && sudo apt-get install -y libyaml-dev
          wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -O clair-scanner
          sudo mv clair-scanner /usr/local/bin
          sudo chmod +x /usr/local/bin/clair-scanner

      - name: Run Clair scan
        run: clair-scanner --ip $(hostname -I) myimage
