name: Clair Dockerfile Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clair_scan:
    name: Clair Dockerfile Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Run Clair V4 update
        uses: quay/clair-action@allow-update
        with:
          db-file: matcher.db
          mode: update
          image-ref: myimage
          format: sarif
          output: clair_results.sarif
  
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clair_results.sarif
