name: Clair Default Action Scan

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  docker-build:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grab cache DB
        uses: actions/cache@v3
        with:
          path: matcher.db
          key: matcher.db

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Run Clair V4
        uses: quay/clair-action@allow-update
        with:
          image-ref: myimage
          db-file: matcher.db
          format: sarif
          output: clair_results.sarif
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sarif
          path: clair_results.sarif
          
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clair_results.sarif

