name: Clair Dockerfile Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clair_scan:
    name: Clair Dockerfile Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Run Clair V4
        uses: quay/clair-action@main
        with:
          image-ref: myimage
